import { useRef } from "react";
import { projects } from "../../Assets/Data/projects/projects";
import Frame from "../Other/Frame";
import Page from "../Page/Page";
import Emphasize from "../Other/Emphasize";
import SectionHeader from "../Other/Section/SectionHeader";
import SectionCard from "../Other/Section/SectionCard";
import { FaExclamation } from "react-icons/fa6";
import ProjectCard from "./ProjectCard";

import gameplay from "/src/Assets/Images/Projects/NeuralNector/game.png";
import yinyang from "/src/Assets/Images/Projects/NeuralNector/yin-yang-flowers.png";

const NeuralNectorPage = () => {
  const neuralNector = projects["Neural Nector"];
  const overview = useRef(null!);
  const gan = useRef(null!);
  const challenges = useRef(null!);
  const game = useRef(null!);

  const contents = {
    overview,
    "GAN Model": gan,
    challenges,
    game,
  };

  return (
    <Page contents={contents} color={neuralNector.color + "80"}>
      <div className="flex-col items-center">
        <h2>
          Neural <span className="text-gradient font-medium">Nector</span>
        </h2>
        <h4 className="font-bold mt-[-1.5rem] ~text-base/xl text-center px-8 text-gray-300">
          <span className="text-white">{neuralNector.time}</span>
          {` — ${neuralNector.description}`}
        </h4>
      </div>

      <div className="flex-col w-[80vw] md:w-[60vw]">
        <div id="overview" ref={overview} className="flex-col gap-10 pt-14">
          <div className="fade-in-up">
            <Frame midClass={"w-full min-w-[325px]"}>
              <div className="glare w-1/3" />
              <img
                src={neuralNector.image}
                alt="Neural Nector"
                className="border border-slate-500 rounded-xl"
              />
            </Frame>
          </div>

          <div className="flex-col gap-4">
            <div className="flex justify-between">
              <SectionHeader text={"Overview"} style={"~text-base/xl"} />
              <div className="flex ~gap-1/4 items-center mr-4">
                {Object.entries(neuralNector.tech).map(([name, item], index) => (
                  <span key={index} className="text-white ~text-lg/3xl" title={name}>
                    {item as React.ReactNode}
                  </span>
                ))}
              </div>
            </div>

            <div className="flex flex-col lg:flex-row ~gap-4/12 ~text-base/lg ~leading-7/8">
              <p className="flex-1">
                <span className="text-white">Neural Nector</span> is an interactive, full-stack web
                app that challenges users to distinguish between real flower images and those
                generated by my <Emphasize text="Generative Adversarial Network (GAN)" />. The app
                scores users on accuracy and speed on a global leaderboard.
              </p>
              <p className="flex-1">
                The application is powered by a <Emphasize text="PyTorch-trained GAN" /> model that
                generates realistic flower images with a <Emphasize text="FID score of 50" />,
                demonstrating moderate-to-high quality synthetic image generation. Can you tell the
                difference? Try it out here:{" "}
                <a
                  href="https://neuralnector.com"
                  target="_blank"
                  className="text-blue-400 underline"
                >
                  Neural Nector
                </a>
              </p>
            </div>
          </div>
        </div>

        <div className="divider ~py-8/20" ref={gan} />

        <div id="GAN_Model" className="flex-col gap-10 ~py-8/20">
          <SectionHeader text={"GAN Model"} style={"~text-xl/3xl"} />

          <div className="flex flex-col lg:flex-row gap-12 items-center h-fit">
            <div className="flex-1 w-full min-w-[325px] flex items-center justify-center">
              <img
                src={yinyang}
                alt="Yin Yang Flowers"
                className="w-full h-full object-cover max-w-[400px]"
              />
            </div>
            <div className="flex-1 flex-col gap-6 ~text-base/lg ~leading-7/8">
              <p>
                <span className="text-white">
                  The Generative Adversarial Network was trained using PyTorch
                </span>{" "}
                to learn the distribution of flower images. The model consists of a{" "}
                <Emphasize text="generator" /> that creates synthetic images and a{" "}
                <Emphasize text="discriminator" /> that tries to distinguish between real and
                generated images.
              </p>
              <p>
                These are then trained with opposite goals, and <Emphasize text="together" /> they
                learn to produce increasingly realistic flower images. The model achieved a{" "}
                <Emphasize text="FID score of 50" />, which indicates that the generated flowers are
                fairly visually convincing and maintain good diversity.
              </p>
            </div>
          </div>
        </div>

        <div className="divider ~py-8/20" ref={challenges} />

        <div id="challenges" className="flex-col ~gap-12/20">
          <SectionCard
            color="#F9D10C"
            symbol={<FaExclamation />}
            title="The Main Challenges"
            text="Mode Collapse"
            className="w-full min-w-[325px]"
          />

          <div className="flex flex-col lg:flex-row gap-6">
            <div className="flex-1">
              <SectionHeader text={"Challenges"} style={"~text-xl/3xl"} />
            </div>
            <div className="flex-1 flex-col gap-6 ~text-base/lg ~leading-7/8">
              <p>
                <span className="text-white">
                  Training a GAN comes with unique challenges, with mode collapse being a common
                  issue.
                </span>{" "}
                Mode collapse occurs when the generator produces{" "}
                <Emphasize text="limited diversity" />, generating very similar or identical images
                instead of learning the full distribution of the data. This happens when the
                generator finds a pattern that consistently fools the discriminator and{" "}
                <Emphasize text="stops exploring" /> other possibilities.
              </p>
              <p>
                To address this, I implemented several solutions including{" "}
                <Emphasize text="extended training" /> to give the generator more time to learn the
                full data distribution, <Emphasize text="batch normalization" /> to stabilize
                training, and careful tuning of the learning rates for both the generator and
                discriminator to keep a <Emphasize text="balanced" /> adversarial training process.
              </p>
            </div>
          </div>
        </div>

        <div className="divider ~pt-8/20" />

        <div id="game" ref={game} className="flex-col gap-10 ~pt-6/14">
          <SectionHeader text={"The Game"} style={"~text-xl/3xl"} />

          <Frame midClass="w-full min-w-[325px]">
            <div className="glare w-1/3" />
            <img
              src={gameplay}
              alt="Neural Nector Game"
              className="border border-[--border-color] rounded-xl w-full h-full object-cover"
            />
          </Frame>

          <div className="flex flex-col lg:flex-row ~gap-4/12 ~text-base/lg ~leading-7/8">
            <p className="flex-1">
              <span className="text-white">
                Neural Nector presents players with a grid of flower images
              </span>{" "}
              and challenges players to select all the fake (AI-generated) flowers. The game
              features <Emphasize text="multiple difficulty levels" /> and scoring based on{" "}
              <Emphasize text="accuracy" /> and <Emphasize text="speed" />, with scores tracked on
              global leaderboards.
            </p>
            <p className="flex-1">
              Built with <Emphasize text="React" />, <Emphasize text="TypeScript" />, and{" "}
              <Emphasize text="PostgreSQL" />. As AI-generated content becomes increasingly
              difficult to distinguish from real content, this game serves as some fun practice for
              identifying <Emphasize text="synthetic media" /> in our increasingly synthetic world.
            </p>
          </div>
        </div>

        <div className="divider ~py-8/20" />
        <div className="flex-col items-center gap-12">
          <h3 className="text-white hero-text-shadow ~text-2xl/4xl font-bold">
            Explore my Last Project
          </h3>
          <ProjectCard project="Turbo3D" />
        </div>
      </div>
    </Page>
  );
};

export default NeuralNectorPage;
