import { useRef } from "react";
import { projects } from "../../Assets/Data/projects/projects";
import Frame from "../Other/Frame";
import Page from "../Page/Page";
import Emphasize from "../Other/Emphasize";
import SectionHeader from "../Other/Section/SectionHeader";
import SectionCard from "../Other/Section/SectionCard";
import SectionList from "../Other/Section/SectionList";
import { FaExclamation } from "react-icons/fa6";
import ProjectCard from "./ProjectCard";

import gameplay from "/src/Assets/Images/Projects/NeuralNector/game.png";
import yinyang from "/src/Assets/Images/Projects/NeuralNector/yin-yang-flowers.png";
import epochsImage from "/src/Assets/Images/Projects/NeuralNector/epochs.png";
import modeCollapse from "/src/Assets/Images/Projects/NeuralNector/flower_collapse.png";

const NeuralNectorPage = () => {
  const neuralNector = projects["Neural Nector"];
  const overview = useRef(null!);
  const gan = useRef(null!);
  const training = useRef(null!);
  const challenges = useRef(null!);
  const game = useRef(null!);

  const contents = {
    overview,
    "GAN Model": gan,
    training,
    challenges,
    game,
  };

  return (
    <Page contents={contents} color={neuralNector.color + "80"}>
      <div className="flex-col items-center">
        <h2>
          Neural <span className="text-gradient font-medium">Nector</span>
        </h2>
        <h4 className="font-bold mt-[-1.5rem] ~text-base/xl text-center px-8 text-gray-300">
          <span className="text-white">{neuralNector.time}</span>
          {` — ${neuralNector.description}`}
        </h4>
      </div>

      <div className="flex-col w-[80vw] md:w-[60vw]">
        <div id="overview" ref={overview} className="flex-col gap-10 pt-14">
          <div className="fade-in-up">
            <Frame midClass={"w-full min-w-[325px]"}>
              <div className="glare w-1/3" />
              <img
                src={neuralNector.image}
                alt="Neural Nector"
                className="border border-slate-500 rounded-xl"
              />
            </Frame>
          </div>

          <div className="flex-col gap-4">
            <div className="flex justify-between">
              <SectionHeader text={"Overview"} style={"~text-base/xl"} />
              <div className="flex ~gap-1/4 items-center mr-4">
                {Object.entries(neuralNector.tech).map(([name, item], index) => (
                  <span key={index} className="text-white ~text-lg/3xl" title={name}>
                    {item as React.ReactNode}
                  </span>
                ))}
              </div>
            </div>

            <div className="flex flex-col lg:flex-row ~gap-4/12 ~text-base/lg ~leading-7/8">
              <p className="flex-1">
                <span className="text-white">Neural Nector</span> is an interactive, full-stack web
                app that challenges users to distinguish between real flower images and those
                generated by my <Emphasize text="Generative Adversarial Network (GAN)" />. The app
                scores users on accuracy and speed on a global leaderboard.
              </p>
              <p className="flex-1">
                The application is powered by a <Emphasize text="PyTorch-trained GAN" /> model that
                generates realistic flower images with a <Emphasize text="FID score of 50" />,
                demonstrating moderate-to-high quality synthetic image generation. {" "}
                <a
                  href="https://neuralnector.com"
                  target="_blank"
                  className="text-blue-400 underline"
                >
                  Can you tell the difference?
                </a>
              </p>
            </div>
          </div>
        </div>

        <div className="divider ~py-8/20" ref={gan} />

        <div id="GAN_Model" className="flex-col gap-10 ~py-8/20">
          <SectionHeader text={"GAN Model"} style={"~text-xl/3xl"} />

          <div className="flex flex-col lg:flex-row gap-12 items-center h-fit">
            <div className="flex-1 w-full min-w-[325px] flex items-center justify-center">
              <img
                src={yinyang}
                alt="Yin Yang Flowers"
                className="w-full h-full object-cover max-w-[400px]"
              />
            </div>
            <div className="flex-1 flex-col gap-6 ~text-base/lg ~leading-7/8">
              <h3 className="text-white ~text-xl/2xl font-bold mb-2">
                How it Works
              </h3>
              <p>
                <span className="text-white">
                  The Generative Adversarial Network was trained using PyTorch
                </span>{" "}
                to learn the distribution of flower images. The model consists of a{" "}
                <Emphasize text="generator" /> that creates synthetic images and a{" "}
                <Emphasize text="discriminator" /> that tries to distinguish between real and
                generated images.
              </p>
              <p>
                These are then trained with opposite goals, and <Emphasize text="together" /> they
                learn to produce increasingly realistic flower images. The model achieved a{" "}
                <Emphasize text="FID score of 50" />, which indicates that the generated flowers are
                fairly visually convincing and maintain good diversity.
              </p>
            </div>
          </div>
        </div>

        <div className="divider ~py-8/20" ref={training} />

        <div id="Training_Progression" className="flex-col gap-10 ~py-8/20">
          <SectionHeader text={"Training Progression"} style={"~text-xl/3xl"} />

          <div className="flex flex-col gap-12">
            <div className="flex flex-col-reverse lg:flex-row gap-12 items-center h-fit">
              <div className="flex-1 flex-col gap-6 ~text-base/lg ~leading-7/8">
                <h3 className="text-white ~text-xl/2xl font-bold mb-2">
                  Two Rivals Sharpening Each Other
                </h3>
                <p>
                  <span className="text-white">At first, both the generator and discriminator</span>{" "}
                  don't know what they're doing. The generator creates random noise, and the
                  discriminator guesses randomly. As the discriminator picks up on the generator's patterns, the generator learns more and more subtle details to fool it.
                </p>
                <p>
                  <span className="text-white">Like two rivals sharpening each other,</span> the generator and discriminator keep improving until the generator is able to create realistic flowers. However, just as two rivals need to be <Emphasize text="equals" /> to sharpen each other, the generator and discriminator must maintain <Emphasize text="balance" />, without one being too strong or too weak. If that becomes the case, both will regress to safe patterns and stop improving (<Emphasize text="Mode Collapse" />).
                </p>
                <p>
                  <span className="text-white">By the end of training,</span> it becomes a challenge for even humans to tell the difference between
                  real and fake flowers (for 64x64 images). That's where this game comes in. You are
                  now the discriminator. Can <Emphasize text="you" /> tell the difference?
                </p>
              </div>
              <div className="flex-1 w-full h-full min-w-[325px] flex items-center justify-center">
                <Frame midClass="w-full">
                  <div className="glare w-1/3" />
                  <img
                    src={epochsImage}
                    alt="Training Progression Across Epochs"
                    className="border border-[--border-color] rounded-xl w-full h-full object-cover"
                  />
                </Frame>
              </div>
            </div>
            <div className="flex-col gap-10">
              {/* lg and up: split into two columns (2x2 grid) */}
              <div className="hidden lg:flex gap-10">
                <SectionList className="flex-1" items={neuralNector.epochs!.slice(0, 2)} color={neuralNector.color} />
                <SectionList className="flex-1" items={neuralNector.epochs!.slice(2, 4)} color={neuralNector.color} />
              </div>

              {/* below lg: all in one column */}
              <div className="block lg:hidden">
                <SectionList items={neuralNector.epochs!} color={neuralNector.color} />
              </div>
            </div>
          </div>
        </div>

        <div className="divider ~py-8/20" ref={challenges} />

        <div id="challenges" className="flex-col ~gap-12/20">
          <SectionCard
            color="#F9D10C"
            symbol={<FaExclamation />}
            title="The Main Challenges"
            text="Mode Collapse"
            className="w-full min-w-[325px]"
          />

          <div className="flex flex-col lg:flex-row gap-12">
            <div className="flex-1">
              <Frame midClass="w-full min-w-[325px]">
                <div className="glare w-1/3" />
                <img
                  src={modeCollapse}
                  alt="Mode Collapse"
                  className="border border-[--border-color] rounded-xl w-full h-full object-cover"
                />
              </Frame>
            </div>
            <div className="flex-1 flex-col gap-6 ~text-base/lg ~leading-7/8">
              <p>
                <span className="text-white">
                  Training a GAN comes with unique challenges, with mode collapse being a common
                  issue.
                </span>{" "}
                Mode collapse occurs when the generator produces similar images
                instead of learning the full distribution. This happens when the
                discriminator outpaces the generator, which then regresses to a safe but incorrect pattern.
              </p>
              <p>
                To address this, I implemented several solutions including{" "}
                <Emphasize text="extended training" /> to give the generator more time to learn the
                full data distribution, <Emphasize text="batch normalization" /> to stabilize
                training, and careful tuning of the learning rates for both the generator and
                discriminator to keep a <Emphasize text="balanced" /> adversarial training process.
              </p>
            </div>
          </div>
        </div>

        <div className="divider ~pt-8/20" />

        <div id="game" ref={game} className="flex-col gap-10 ~pt-6/14">
          <SectionHeader text={"The Game"} style={"~text-xl/3xl"} />

          <Frame midClass="w-full min-w-[325px]">
            <div className="glare w-1/3" />
            <img
              src={gameplay}
              alt="Neural Nector Game"
              className="border border-[--border-color] rounded-xl w-full h-full object-cover"
            />
          </Frame>

          <div className="flex flex-col lg:flex-row ~gap-4/12 ~text-base/lg ~leading-7/8">
            <p className="flex-1">
              <span className="text-white">
                Neural Nector presents players with a grid of flower images
              </span>{" "}
              and challenges players to select all the fake (AI-generated) flowers. The game
              features <Emphasize text="multiple difficulty levels" /> and scoring based on{" "}
              <Emphasize text="speed" /> and <Emphasize text="correctness" />, tracked on global
              leaderboards.
            </p>
            <p className="flex-1">
              The scoring system is designed to be fair and challenging, with the{" "}
              <Emphasize text="correctness" />
              being calculated using the <Emphasize text="F1 metric" /> to penalize False Positives
              (calling a real flower fake) and False Negatives (missing a fake) to discourage
              guessing.
            </p>
          </div>
        </div>

        <div className="divider ~py-8/20" />
        <div className="flex-col items-center gap-12">
          <h3 className="text-white hero-text-shadow ~text-2xl/4xl font-bold">
            Explore my Last Project
          </h3>
          <ProjectCard project="Turbo3D" />
        </div>
      </div>
    </Page>
  );
};

export default NeuralNectorPage;
